### ISSUE TITLE
No matching distribution found for futures==3.2.0 (from -r requirements.txt (line 6))

### ISSUE THREAD

**Issue by francesco1119** [dchrastil/ScrapedIn#30]
I just tried to run `sudo pip install -r requirements.txt` and this is the result: 

```
Collecting beautifulsoup4==4.6.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/9e/d4/10f46e5cfac773e22707237bfcd51bbffeaf0a576b0a847ec7ab15bd7ace/beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 1.8MB/s
Collecting certifi==2023.7.22 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 3.4MB/s
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (3.0.4)
Collecting cryptography==41.0.6 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/4d/b4/828991d82d3f1b6f21a0f8cfa54337ed33fdb52135f694130060839cfc33/cryptography-41.0.6.tar.gz (630kB)
    100% |████████████████████████████████| 634kB 2.5MB/s
  Installing build dependencies ... done
Collecting enum34==1.1.6 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
Collecting futures==3.2.0 (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement futures==3.2.0 (from -r requirements.txt (line 6)) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
No matching distribution found for futures==3.2.0 (from -r requirements.txt (line 6))
```

So I tried to run  `python ScrapedIn.py` and I receive: 

```
Traceback (most recent call last):
  File "ScrapedIn.py", line 22, in <module>
    from thready import threaded
ModuleNotFoundError: No module named 'thready'
```

So I try to install it through `pip install threaded` and it works: 

```
Collecting threaded
  Downloading https://files.pythonhosted.org/packages/13/e4/87977aafea1cb6c1f7064f5bd6eaad0f7fadc30c82b21c0bce695c4455c0/threaded-4.1.0-cp37-cp37m-manylinux1_x86_64.whl (813kB)
    100% |████████████████████████████████| 819kB 1.7MB/s
Installing collected packages: threaded
Successfully installed threaded-4.1.0
```

I now try again `python ScrapedIn.py` and I have: 

```
Traceback (most recent call last):
  File "ScrapedIn.py", line 22, in <module>
    from thready import threaded
ModuleNotFoundError: No module named 'thready'
```

There must be some problem with that library

**Comment by dchrastil** [comment]
Thanks! I’ll clean up the requirements file

**Comment by uhaba** [comment]
> It does not work on Python 3 due to Python 2 syntax being used in the codebase. Python 3 users should not attempt to install it, since the package is already included in the standard library.

from [https://pypi.org/project/futures/](https://pypi.org/project/futures/)

**Comment by Script-Nomad** [comment]
This issue is still present. Fix is to replace `future==3.2.2` with the current latest supported python3 library: `future==3.0.5` in the requirements.txt file.

Didn't seem worthy of a PR, but figured this would help people in the meantime until a fix was merged.
