### ISSUE TITLE
Traceback Error : TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by akashrpatil** [dchrastil/ScrapedIn#34]
Traceback (most recent call last):
  File "/home/admin/Tools/ScrapedIn/ScrapedIn.py", line 358, in <module>
    companyResults = companyLookup(companyName)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Tools/ScrapedIn/ScrapedIn.py", line 152, in companyLookup
    if c['item']['entityResult']['title']['text']:
       ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by andersonn-cardoso** [comment]
the same issue!
![Image](https://github.com/user-attachments/assets/f2d8e7ba-bf0c-423e-954f-2c67d8e55ab1)

**Comment by amineelhailaa** [comment]
same issue no fix ??
