### ISSUE TITLE
Multiple Errors while running python script. 

### ISSUE THREAD

**Issue by C0deDaedalus** [dchrastil/ScrapedIn#7]
Hi,
I am running Ubuntu 16.04 (KDE) 64-bit machine. After installing `xlsxwriter` and `thready` I ran the script and got this error.

        [Info] Obtained new session: error
        Traceback (most recent call last):
        File "./ScrapedIn.py", line 156, in <module>
            get_search()
        File "./ScrapedIn.py", line 41, in get_search
            r = requests.get(url, cookies=cookies, headers=headers)
        File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
            return request('get', url, params=params, **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
            return session.request(method=method, url=url, **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
            resp = self.send(prep, **send_kwargs)
        File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 640, in send
            history = [resp for resp in gen] if allow_redirects else []
        File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 140, in resolve_redirects
            raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
        requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
        Exception Exception: Exception('Exception caught in workbook destructor. Explicit close() may be required for workbook.',) in <bound method Workbook.__del__ of <xlsxwriter.workbook.Workbook object at 0x7f7e40cf9cd0>> ignored

Please check it and update with solution.

Thanks.

**Comment by dchrastil** [comment]
This is resolved in the new version.
